// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIk8P76VToK_GD07V_80E4OZ0vMlFg-c',
    appId: '1:104787327077:web:b58d279dda8a686ca1ae8c',
    messagingSenderId: '104787327077',
    projectId: 'roboserve-fd298',
    authDomain: 'roboserve-fd298.firebaseapp.com',
    storageBucket: 'roboserve-fd298.appspot.com',
    measurementId: 'G-Y1JHCW5H4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChuJFRKD_bFRFw-3yxDwHr7FQp05k93Sg',
    appId: '1:104787327077:android:c512aced40867298a1ae8c',
    messagingSenderId: '104787327077',
    projectId: 'roboserve-fd298',
    storageBucket: 'roboserve-fd298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHK4h5-G3rh7x9-f3p7PXNnhnmggrd6yo',
    appId: '1:104787327077:ios:28413b0d98f176d0a1ae8c',
    messagingSenderId: '104787327077',
    projectId: 'roboserve-fd298',
    storageBucket: 'roboserve-fd298.appspot.com',
    iosBundleId: 'com.roboserve.roboServeMobilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHK4h5-G3rh7x9-f3p7PXNnhnmggrd6yo',
    appId: '1:104787327077:ios:28413b0d98f176d0a1ae8c',
    messagingSenderId: '104787327077',
    projectId: 'roboserve-fd298',
    storageBucket: 'roboserve-fd298.appspot.com',
    iosBundleId: 'com.roboserve.roboServeMobilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIk8P76VToK_GD07V_80E4OZ0vMlFg-c',
    appId: '1:104787327077:web:885923effe86a152a1ae8c',
    messagingSenderId: '104787327077',
    projectId: 'roboserve-fd298',
    authDomain: 'roboserve-fd298.firebaseapp.com',
    storageBucket: 'roboserve-fd298.appspot.com',
    measurementId: 'G-ETKR38RE9R',
  );
}
